[connections.snowflake]
account = "LDTTVLQ-AVB38604"      
user = "IVINALORENAMOURA"               
password = "IvinaLorena!0712"           
role = "ACCOUNTADMIN"               
warehouse = "COMPUTE_WH"            
database = "SNOWFLAKE_LEARNING_DB"  
schema = "PUBLIC"                   